version: '3'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: project_template
      MYSQL_PASSWORD: 123456

  react-app:
    build:
      context: ../FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - spring-app